# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.resourceDirectoryLabel = QtWidgets.QLabel(Form)
        self.resourceDirectoryLabel.setObjectName("resourceDirectoryLabel")
        self.gridLayout.addWidget(self.resourceDirectoryLabel, 0, 0, 1, 1)
        self.resourceDirectoryLineEdit = QtWidgets.QLineEdit(Form)
        self.resourceDirectoryLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.resourceDirectoryLineEdit.setFrame(True)
        self.resourceDirectoryLineEdit.setReadOnly(False)
        self.resourceDirectoryLineEdit.setClearButtonEnabled(True)
        self.resourceDirectoryLineEdit.setObjectName("resourceDirectoryLineEdit")
        self.gridLayout.addWidget(self.resourceDirectoryLineEdit, 0, 1, 1, 1)
        self.resourceDirectoryDialogButton = QtWidgets.QToolButton(Form)
        self.resourceDirectoryDialogButton.setObjectName("resourceDirectoryDialogButton")
        self.gridLayout.addWidget(self.resourceDirectoryDialogButton, 0, 2, 1, 1)
        self.destinationDirectoryLabel = QtWidgets.QLabel(Form)
        self.destinationDirectoryLabel.setObjectName("destinationDirectoryLabel")
        self.gridLayout.addWidget(self.destinationDirectoryLabel, 1, 0, 1, 1)
        self.destinationDirectoryLineEdit = QtWidgets.QLineEdit(Form)
        self.destinationDirectoryLineEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.destinationDirectoryLineEdit.setReadOnly(False)
        self.destinationDirectoryLineEdit.setClearButtonEnabled(True)
        self.destinationDirectoryLineEdit.setObjectName("destinationDirectoryLineEdit")
        self.gridLayout.addWidget(self.destinationDirectoryLineEdit, 1, 1, 1, 1)
        self.destinationDirectoryDialogButton = QtWidgets.QToolButton(Form)
        self.destinationDirectoryDialogButton.setObjectName("destinationDirectoryDialogButton")
        self.gridLayout.addWidget(self.destinationDirectoryDialogButton, 1, 2, 1, 1)
        self.audioFormatLabel = QtWidgets.QLabel(Form)
        self.audioFormatLabel.setObjectName("audioFormatLabel")
        self.gridLayout.addWidget(self.audioFormatLabel, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(25, 19, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.audioFormatComboBox = QtWidgets.QComboBox(Form)
        self.audioFormatComboBox.setObjectName("audioFormatComboBox")
        self.audioFormatComboBox.addItem("")
        self.audioFormatComboBox.addItem("")
        self.gridLayout.addWidget(self.audioFormatComboBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonsFrame = QtWidgets.QFrame(Form)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.buttonsLayout = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.convertProgressBar = QtWidgets.QProgressBar(self.buttonsFrame)
        self.convertProgressBar.setMaximum(100)
        self.convertProgressBar.setProperty("value", 0)
        self.convertProgressBar.setInvertedAppearance(False)
        self.convertProgressBar.setObjectName("convertProgressBar")
        self.buttonsLayout.addWidget(self.convertProgressBar)
        self.scanButton = QtWidgets.QPushButton(self.buttonsFrame)
        self.scanButton.setEnabled(False)
        self.scanButton.setObjectName("scanButton")
        self.buttonsLayout.addWidget(self.scanButton)
        self.convertButton = QtWidgets.QPushButton(self.buttonsFrame)
        self.convertButton.setEnabled(False)
        self.convertButton.setObjectName("convertButton")
        self.buttonsLayout.addWidget(self.convertButton)
        self.verticalLayout.addWidget(self.buttonsFrame)
        self.informationLabel = QtWidgets.QLabel(Form)
        self.informationLabel.setObjectName("informationLabel")
        self.verticalLayout.addWidget(self.informationLabel)
        self.informationTextEdit = QtWidgets.QTextEdit(Form)
        self.informationTextEdit.setUndoRedoEnabled(False)
        self.informationTextEdit.setReadOnly(True)
        self.informationTextEdit.setObjectName("informationTextEdit")
        self.verticalLayout.addWidget(self.informationTextEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Audio Converter"))
        self.resourceDirectoryLabel.setText(_translate("Form", "Resource Directory"))
        self.resourceDirectoryLineEdit.setPlaceholderText(_translate("Form", "Path to raw audio"))
        self.resourceDirectoryDialogButton.setText(_translate("Form", "..."))
        self.destinationDirectoryLabel.setText(_translate("Form", "Destination Directory"))
        self.destinationDirectoryLineEdit.setPlaceholderText(_translate("Form", "Path to converted audio"))
        self.destinationDirectoryDialogButton.setText(_translate("Form", "..."))
        self.audioFormatLabel.setText(_translate("Form", "Audio Format"))
        self.audioFormatComboBox.setItemText(0, _translate("Form", "mp3"))
        self.audioFormatComboBox.setItemText(1, _translate("Form", "flac"))
        self.scanButton.setText(_translate("Form", "Scan"))
        self.convertButton.setText(_translate("Form", "Convert"))
        self.informationLabel.setText(_translate("Form", "Information"))
        self.informationTextEdit.setPlaceholderText(_translate("Form", "Welcome! Choose resource and destination directory to start."))

